"""add schema full text search

Revision ID: 31c76304e38b
Revises: a05d2d3c7303
Create Date: 2026-09-21 19:30:29.321426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c76304e38b'
down_revision: Union[str, Sequence[str], None] = 'a05d2d3c7303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_documents', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, content)", persisted=True), nullable=False))
    op.create_index('ix_schema_documents_search_vector', 'schema_documents', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schema_documents_search_vector', table_name='schema_documents', postgresql_using='gin')
    op.drop_column('schema_documents', 'search_vector')
    # ### end Alembic commands ###
