"""add schema document registry

Revision ID: 37606873a0bc
Revises: 73f54ee6b6a3
Create Date: 2026-09-15 14:36:56.777476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '37606873a0bc'
down_revision: Union[str, Sequence[str], None] = '73f54ee6b6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(length=63), nullable=False),
    sa.Column('table_name', sa.String(length=63), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_name', 'table_name', name='uq_schema_documents_schema_table')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_documents')
    # ### end Alembic commands ###
