"""create core olist tables

Revision ID: 73e4b3d749f6
Revises: 
Create Date: 2026-09-12 22:25:56.463436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e4b3d749f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('customer_unique_id', sa.String(length=32), nullable=False),
    sa.Column('customer_zip_code_prefix', sa.Integer(), nullable=False),
    sa.Column('customer_city', sa.String(length=100), nullable=False),
    sa.Column('customer_state', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('product_category_name', sa.String(length=100), nullable=True),
    sa.Column('product_name_length', sa.Integer(), nullable=True),
    sa.Column('product_description_length', sa.Integer(), nullable=True),
    sa.Column('product_photos_qty', sa.Integer(), nullable=True),
    sa.Column('product_weight_g', sa.Integer(), nullable=True),
    sa.Column('product_length_cm', sa.Integer(), nullable=True),
    sa.Column('product_height_cm', sa.Integer(), nullable=True),
    sa.Column('product_width_cm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('order_status', sa.String(length=20), nullable=False),
    sa.Column('order_purchase_timestamp', sa.DateTime(), nullable=False),
    sa.Column('order_approved_at', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_carrier_date', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_customer_date', sa.DateTime(), nullable=True),
    sa.Column('order_estimated_delivery_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('seller_id', sa.String(length=32), nullable=False),
    sa.Column('shipping_limit_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('freight_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'order_item_id')
    )
    op.create_table('order_payments',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('payment_sequential', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=30), nullable=False),
    sa.Column('payment_installments', sa.Integer(), nullable=False),
    sa.Column('payment_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'payment_sequential')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_payments')
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
